<?php
/**
 * Copyright © Graycore. All rights reserved.
 */
?>
<script>
window.CmsAiBuilderUrl = '<?= $block->getUrl('CmsAiBuilder/generate/index') ?>';
window.CmsAiBuilderAssetsPath = '<?= $block->getViewFileUrl('Graycore_CmsAiBuilder::js/admin-preview') ?>';

// Configure Monaco environment for web workers
window.MonacoEnvironment = {
  getWorkerUrl: (_moduleId, label) => {
    if (label === 'json') {
      return window.CmsAiBuilderAssetsPath + '/assets/monaco/min/vs/assets/json.worker-DghZTZS7.js';
    }
    return window.CmsAiBuilderAssetsPath + '/assets/monaco/min/vs/assets/editor.worker-DM0G1eFj.js';
  },
};
</script>
